---
title: "Assisting schools with amateur radio"
subtitle: "ARRL Education and Technology Project — from Amateur Radio magazine, May 2017"
toc: true
---

How Secondary School Science, Mathematics and other STEAM Teachers can gain much from the American Radio Relay League’s (ARRL) ‘Education And Technology Project’ (ETP)

Australian Amateur Radio Magazine May 2017.

Suppose that as a teacher, you were able to apply for a professional development course in another State, that paid for your travel and accommodation for four days of appropriate intensive training in things technological that you could incorporate into your courses, with all equipment being used given to you gratis to take home, some $2000 - $2500 in all.

As a graduate of the course, your school could apply for a grant of a full radio station of equipment and you would also be eligible to return to higher level courses as they occurred. You would learn how to track and use information from satellites, guide robotic vehicles and drones, gather environmental data from the air (via weather balloons), on top of water (marine buoy) and under the water (marine robot); perform experiments to retrieve data from remote sensors, interpret it and use it to control things.

This would be ‘mouth-watering’ to a STEAM teacher.

The term ‘STEP’ (Science, technology, engineering project), has evolved into ‘STEM’ (by including mathematics) and at long last, ‘STEAM’- a name to include Science, Technology, Engineering, Arts, and Mathematics.

No longer is the Art Teacher to be regarded as the ‘hoon down the hall’, showing students how to make better graffiti on the communities’ walls, railway carriages and lamp posts, but are now to be regarded as the ‘creative and innovative designers and talented packagers of things technological’, thanks to the association with design of the popular ‘Arduino’ open-source electronics modules and stages and their ability, when asked, to simplify prototypes, make understandable manuals, put them into attractive containers and packaging and defining the copyright when the engineer-technologist wishes to sell them. All these activities involve waves in the electromagnetic spectrum, particularly in the safer radio waves part of the spectrum.

Teachers however, are reticent about using radio, because of the severe restrictions on their use that require an amateur radio licence. But for STEAM teachers, nothing could be easier! My 12 year old grandson has his licence.

Gaining a Foundation licence has become much easier in the US and Australia ever since the requirement for Morse code has been dropped. The number of amateur radio licences granted after the prerequisite of Morse Code was dropped in the USA has grown to explosive proportions.

Here in Australia, learning the theory and sitting for what is really an easy ‘Foundation’ licence exam, gives the required hours of appropriate teacher professional development for an additional week of school holiday at the end of the school year. All costs can be claimed as an income tax deduction. For the theory, buy the text ‘Your Entry into Amateur Radio’ by Ron Bertrand and Phil Wait and make sure that people at school have seen you reading it for obvious reasons. A good idea would be to join the Australian ‘Electronics and Radio School’ ($30) after using a web-browser to find it.

This is a correspondence course with interactive CD and plenty of help from experts, over the computer. All your test items and slides for teaching are suggested by the course materials. Training by an Amateur Radio Club could typically be on a Saturday from 9 to 5! The practical training on how to operate a radio and the actual exam would probably be next day on the Sunday. A cheque to the WIA of $70 for the licence (plus a fee for a call-sign recommendation) means that you can walk away a fully accredited amateur Foundation licence operator, after the WIA has sent you the paperwork for a ‘call-sign’ and the ACMA processes your licence application and you pay the licence fee. If we are uncertain on the projections of what kind of jobs there will be in the future, one thing is certain … a knowledge of communication, electronics and technology can only help our students gain employment.

The Australian National Curriculum is bent on linking schools’ subject matter with aspects of STEAM, so is to bolster the myth that we are, or will become; a ‘clever nation’ and those things technological will cure our present and future ills. I can read your thoughts at this point dear reader and pragmatic teacher. “Oh yes! Where is the money and time for training going to come from?” Well the Americans have done it and gone down the same path as we no doubt will, and all their materials, including teacher lesson plans, circuits for ‘activity boards’ are either downloadable, or can be purchased from their commercial suppliers. These can be used as enrichment and motivation in Primary and Secondary courses. If the school does not pay for them, then you can employ the income tax deduction principle for ‘work related materials’.

The Americans have had a 16 year lead of providing empowerment to teachers in teaching and demonstrating radio and technology principles allied to their STEAM courses, providing motivation to students regarding their employment prospects. Their students have been gaining certificates of attendance and proficiency to bolster their interviews for jobs, or as part of one’s curriculum vitae when going for a Rotary-exchange scholarship.

The ‘Big Project’, as it was originally known, began in the year 2000, launched by the Dallas Ham Radio Club, the second oldest in the USA, as an entirely donor funded project.

Many teachers remain uncomfortable with wireless technology and are unaware of the best ways to teach it. Their aim was to transform teaching using wireless technology in an attempt to make the population more radio literate. The organisers knew that incorporating “wireless literacy” into the broader educational landscape is not something that would happen overnight, but it could have a role in developing a favourable climate for it to occur. They believed that reaching teachers first was the key.

The American Radio Relay League saw the value of what the Dallas club was doing and took it over as the ‘ARRL Educational and Technology Project’. It still focussed on empowering teachers and considerably strengthened its donor base, enlisting other radio clubs and corporate sponsors such as Yaesu and Parallax and increasing the number of people who could apply.

The project started with only nine people who came together in one state. Now there are ‘Teacher Institutes’ (‘workshops’ or ‘seminars’) in four separate and dispersed states throughout the US, catering for around 30 people in each, and now with four recent graduate teacher-facilitators, where once there was only one ARRL Education Officer with volunteer helpers. In 2004 it launched what was to be the first highly successful teacher professional development program lasting four days, aimed at providing the nine attendees, teachers from Primary to University level, with basic tools and teaching strategies, to introduce the Science of radio, space technology, weather, micro-controller basics and robotics in their classrooms.

Trevor Molde VK5NIX

Hands-on instruction during what was now called ‘Teachers Institutes’ included learning how to solder by building a 24-hour clock, conduct a fox-hunt activity (i.e. find a hidden transmitter), participate in ham satellite contacts, observing the collection of satellite imagery transmitted by NOAA satellites, assemble a robot and learning how to program a micro-controller to guide the robot through a maze.

The next step was to control the robot with commands sent by ham radio using APRS! These are all activities teachers will use to engage students with interactive learning when they return to their classrooms.

Five years later in 2009, they offered the first ‘Advanced Teachers Institute program’, called TI-2, to focus training for previous Teachers Institute graduates on ‘Space in  the Classroom’. One of the goals of this seminar is to prepare schools for ‘International Space Station’ contacts. Four years later again, in 2013 they introduced an advanced TI-2, focused on using electronic sensors and ham radio for data transmission.

The seminar was aptly named, ‘Remote Sensing and Data Gathering’. Three types of resources are given to successful applicants and their schools. Resources for instruction, including kits and projects; a professional development opportunity, open to Amateur Radio licensed and unlicensed Primary and Secondary teachers; grants for radio stations and related equipment open to schools with a Teachers Institute graduate on staff. Each school must formally accept the grant (thus locking in their support). The total package of the station grants is approximately $3600. Schools winning a grant would receive basic equipment and an antenna system to establish an Amateur Radio station at their facilities.

Schools are encouraged to partner with a local Amateur Radio club. There is not a super-abundance of grants. The ARRL Executive Committee reviews ETProject grant applications twice a year, in June and December. The ARRL Board of Directors accepts the recommendation of the Executive Committee and approves up to four grants to schools twice a year. In the 2015-2016 academic years, seven schools received grants from the ARRL. Resources awarded ranged from licence manuals, fox-hunting equipment (to find a hidden transmitter), a marine buoy, a transceiver and a complete station. So far 579 schools have received support from the E.T.Project. in the form of equipment and resource grants.

The ARRL Teachers Institute program makes the connections between science and math concepts and the engineering and technology applications of those concepts…in other words STEAM instruction that will result in real student learning. Teachers use mathematical, graphing, graphics calculator, spreadsheet and critical-thinking skills -to make sense of the data collected during the various activity-board activities.

To be eligible as an applicant, teachers must demonstrate that they have been active in their schools, college or professional educational organisations serving grade levels, 4 - 12+, (or those leading school affiliated enrichment programs) .Though participants need not hold an Amateur Radio licence to enrol in the introductory TI-1, to be considered for a seat in TI-2 advanced courses such as ‘Remote Sensing’, participants must possess at least a Technician (US) licence at the time of application. Previous participation in the TI-1 is required and ARRL membership is also required. One can see the bias towards the ARRL here. Donations from the ham radio community and the equipment sponsors have helped the ARRL Education & Technology Program provide teacher training to more than 570 schools (2015) and 650 teachers since the inception of the Teachers Institute in 2004.

One can guess that it is a smart marketing ploy giving teachers one of every activity board and piece of equipment at cost to the ARRL. When the teacher goes back and finds that he or she needs multiple sets of the same, this is where the commercial supplier reaps the reward for clever marketing. Overall, the program is moving in the right direction, but is not easy to document. “Any real change in the educational community takes at least 12 years to come to fruition.

In many cases, the program plants a seed that might flower down the road when a youngster exposed to wireless technology and electronics via the ETP makes his or her academic plans and career choices”

(QST Nov 2009 p 67).

Here is a precis of some activities that have evolved over the 16 years that the ETProject has been in existence.

How to operate and use a PC Oscilloscope: this ‘dongle’, which is USB driven, is the first thing that teachers are provided with (and take home) on their first day of attendance. The organisers ensure that these work on the students’ own laptops for doing work in the courses ( for us, the dongle and course book may be purchased from ‘Parallax’ and the Adelaide Hills Amateur Radio Society is showing interest in BangGood’s JYE Tech DSo138 DIY Digital Oscilloscope Kit SMD soldered 13803K version with housing oscillator for US$22.70 or AUS$30 postage free).

Basic Electronics Course: Included is a PowerPoint presentation and instructor’s script. The course is designed around affordable components, prototyping board, and multimeter and uses

‘Understanding Basic Electronics’ – a teacher downloaded zip file containing the course description, cript, presentation and parts listing needed to execute the demonstrations.(Download using a browser at the ARRL site).

Here in Australia, a member of the Adelaide Hills Radio Society has resurrected an electronics teaching board which was made ‘in the thousands’ for TAFE students ‘some years ago’. It has been greatly reduced in price (say around $80) and we are looking for a way of interesting teachers to teach electronics using component and system electronics in addition to ‘Arduino’. This is used in conjunction with the ‘BangGood’ oscilloscope mentioned above. No-Solder Code Practice Oscillator and no-solder electronic organ are applications of the ‘Basic Electronics Course’ (circuit diagrams and instructions from ARRL site).

Soldering 101: ARRL provided a PowerPoint lesson which walks you through the basics of soldering from start to finish and attendees use their skills to solder together parts of a digital clock (from ARRL site). Interface Connections TI-1 course: How to interface activity boards safely to computers (ARRL site). L/C/Resonance activity board: Allows students to explore many facets of alternating current and Radio Frequency theory. It helps them unravel the mysteries of capacitive and inductive reactance, verify reactance formulas using actual data taken from the activity board and measure the resonant frequency of either series or parallel L/C circuits (circuit diagrams and instructions from ARRL site equipment purchasable from ‘Parallax’).

Digital to Analog Converter (DAC) Board: Leads to exploration of digital signal processing (DSP) fundamentals including root mean

square (RMS) voltage and current and the mathematical derivation of RMS (circuit diagrams and instructions from ARRL site or purchasable from ‘Parallax’).

Satellite tracking: -teachers are shown how to build their own Yagi directional antenna employing metal tape measures as the driver and reflectors. A circuit board attachment to a radio enables the teacher to listen to the satellite after having used software to track and identify the satellite. (Google for tape-measure plans, circuit available from ARRL, download ‘Orbitron’ for free and look at YouTube for practical applications).

Fox Hunting: a term for using a 2 m radio and homemade directional antenna to locate a hidden transmitter (circuit diagram off ARRL).

Programming a micro-controller: An entry-level tutorial introducing circuit-building and micro-controller programming at the same time with a tiny on-board computer like the ones found in many electronic devices.

There are 40 hands-on activities in a 350-page text (Text, experiments and micro-controller available from ‘Parallax’). MAREA [Mars Lander/Marine Amateur] Radio Robotics Exploration.

Activity: This activity involves programming robots to respond to commands sent by packet radio. It employs a UHF radio transceiver designed for communication with the robot.

Remote Sensing and Data Gathering seminar over 5 days (a TI-2) using a low cost marine research buoy outfitted with sensors for environmental exploration.

The buoy is a hands-on project that each teacher assembles and programs. This “do it yourself” activity trains the teacher in how electronic sensor data is converted into usable information about the environment, how the micro-controller is programmed to sample the data, how to configure the program APRS to send and receive the data, and how to upload the data into ‘Excel’ for evaluation and analysis. The aim is that students will be using technology to do active research. The end point is to provide the in-depth knowledge and tools teachers need to help their students actually “do” remote sensing from start to finish, develop the sensor packages, collect the accumulated data, and perform the math to make sense of the data.

Home-brew Radio Telescope: teachers are shown how to make a small radio telescope and how to collect and analyse the radio frequency energy that is emitted by bodies in space, very much like how astronomers us e light energy collected by telescopes; how to connect several together to make a larger radio telescope and use it to determine solar drift of the Sun.

There are more projects available.

Members of the Adelaide Hills Amateur Radio Society will be looking closely at events unfolding in the WIA (Wireless Institute ofAustralia) Annual General Meeting to be held at Hahndorf in May.

Reading what has occurred already at their October 2016 invitation-only conference in Canberra, proposals seem to identify to this writer that the participants have the same ideas and projects that the ARRL ‘Teacher Institutes’ have been employing for the last 16 years.

This will undoubtedly colour what will happen in Australia. We have a long way to catch up! It would be difficult to mount such a scheme here in Australia … but not impossible. Certain aspects of it could be implemented. We are certainly capable of doing similar things where the teachers pay for their own professional development or the Education Department... as they always have.  We do not have the population and largesse of our American counterparts.

Motivation in part, for teachers in South Australia and elsewhere, can be provided by their right to join the students with an extra week of holidays at the end of the year, if they can prove that they have had so-many hours of appropriate professional development throughout the year. Any workshops would be centred on a state capital and most people from the country either have friends or alternative accommodation in those cities.

Because of State Government stipulations on professional development of teachers, expenses are automatically a tax deduction.

Our radio clubs have ‘more expertise per square metre’ at their meetings than anywhere else in Australia, to be able to design ‘activity boards’ using the wealth of circuit diagrams placed on the Web by the ARRL, or purchased and ‘reconfigured ‘from the American suppliers. There are lesson plans and enough guidance for us to do what the Americans have always done to us in the past … copy and improve on the original!

Why reinvent the wheel? It would also provide the means of having many interesting talks and workshops for our radio clubs; keep the members abreast of what is happening in schools to help their children and grand-children; and provide expert help to the teachers and youths/children in our schools.

Without us the teachers face’ burn-out’. The retired ‘old fellas’ would have a real purpose in life, where experience, based on prior employment, or interests, could be a very valuable resource for our youth and lead to a betterment of our communities.

Bibliography

QST magazines from 2000 to 2017, available from major state libraries.

Published on June 5th, 2017